// This file was generated by the create_regs script
#define ACR_BASE                                                 0x7e80a000
#define ACR_APB_ID                                               0x61726272
#define ACR_control                                              HW_REGISTER_RW( 0x7e80a000 ) 
   #define ACR_control_MASK                                      0x0000ffff
   #define ACR_control_WIDTH                                     16
   #define ACR_control_RESET                                     0000000000
