// This file was generated by the create_regs script
#define DPI_BASE                                                 0x7e208000
#define DPI_APB_ID                                               0x44504920
#define DPI_C                                                    HW_REGISTER_RW( 0x7e208000 ) 
   #define DPI_C_MASK                                            0x0000ffff
   #define DPI_C_WIDTH                                           16
   #define DPI_C_RESET                                           0x00003000
