// This file was generated by the create_regs script
#define PRM_BASE                                                 0x7e20d000
#define PRM_CS                                                   HW_REGISTER_RW( 0x7e20d000 ) 
   #define PRM_CS_MASK                                           0xffffffff
   #define PRM_CS_WIDTH                                          32
#define PRM_CV                                                   HW_REGISTER_RW( 0x7e20d004 ) 
   #define PRM_CV_MASK                                           0xffffffff
   #define PRM_CV_WIDTH                                          32
#define PRM_SCC                                                  HW_REGISTER_RW( 0x7e20d008 ) 
   #define PRM_SCC_MASK                                          0xffffffff
   #define PRM_SCC_WIDTH                                         32
