// This file was generated by the create_regs script
#define CCP2TX_BASE                                              0x7e001000
#define CCP2TX_APB_ID                                            0x63637032
#define CCP2TX_TC                                                HW_REGISTER_RW( 0x7e001000 ) 
   #define CCP2TX_TC_MASK                                        0xffffffff
   #define CCP2TX_TC_WIDTH                                       32
#define CCP2TX_TS                                                HW_REGISTER_RW( 0x7e001004 ) 
   #define CCP2TX_TS_MASK                                        0xffffffff
   #define CCP2TX_TS_WIDTH                                       32
#define CCP2TX_TPC                                               HW_REGISTER_RW( 0x7e001008 ) 
   #define CCP2TX_TPC_MASK                                       0xffffffff
   #define CCP2TX_TPC_WIDTH                                      32
#define CCP2TX_TSC                                               HW_REGISTER_RW( 0x7e00100c ) 
   #define CCP2TX_TSC_MASK                                       0xffffffff
   #define CCP2TX_TSC_WIDTH                                      32
#define CCP2TX_TIC                                               HW_REGISTER_RW( 0x7e001010 ) 
   #define CCP2TX_TIC_MASK                                       0xffffffff
   #define CCP2TX_TIC_WIDTH                                      32
#define CCP2TX_TTC                                               HW_REGISTER_RW( 0x7e001014 ) 
   #define CCP2TX_TTC_MASK                                       0xffffffff
   #define CCP2TX_TTC_WIDTH                                      32
#define CCP2TX_TBA                                               HW_REGISTER_RW( 0x7e001018 ) 
   #define CCP2TX_TBA_MASK                                       0xffffffff
   #define CCP2TX_TBA_WIDTH                                      32
#define CCP2TX_TDL                                               HW_REGISTER_RW( 0x7e00101c ) 
   #define CCP2TX_TDL_MASK                                       0xffffffff
   #define CCP2TX_TDL_WIDTH                                      32
#define CCP2TX_TD                                                HW_REGISTER_RW( 0x7e001020 ) 
   #define CCP2TX_TD_MASK                                        0xffffffff
   #define CCP2TX_TD_WIDTH                                       32
