// This file was generated by the create_regs script
#define CD_BASE                                                  0x1820b000
#define CD_APB_ID                                                0x43445000
#define CD_CS                                                    HW_REGISTER_RW( 0x1820b000 ) 
   #define CD_CS__MASK                                           0xffffffff
   #define CD_CS__WIDTH                                          32
   #define CD_CS__RESET                                          0000000000
      #define CD_CS__MSB                                         31
      #define CD_CS__LSB                                         0
#define CD_PHYADJ                                                HW_REGISTER_RW( 0x1820b004 ) 
   #define CD_PHYADJ__MASK                                       0x0000ffff
   #define CD_PHYADJ__WIDTH                                      16
      #define CD_PHYADJ__MSB                                     15
      #define CD_PHYADJ__LSB                                     0
#define CD_PHYDAT                                                HW_REGISTER_RO( 0x1820b008 ) 
   #define CD_PHYDAT__MASK                                       0xffffffff
   #define CD_PHYDAT__WIDTH                                      32
      #define CD_PHYDAT__MSB                                     31
      #define CD_PHYDAT__LSB                                     0
