// This file was generated by the create_regs script
#define A2W_PASSWORD                                             0x5a000000
#define A2W_BASE                                                 0x7e102000
#define A2W_APB_ID                                               0x00613277
#define A2W_PLLA_DIG0                                            HW_REGISTER_RW( 0x7e102000 ) 
   #define A2W_PLLA_DIG0_MASK                                    0x00ffffff
   #define A2W_PLLA_DIG0_WIDTH                                   24
   #define A2W_PLLA_DIG0_RESET                                   0000000000
#define A2W_PLLA_DIG1                                            HW_REGISTER_RW( 0x7e102004 ) 
   #define A2W_PLLA_DIG1_MASK                                    0x00ffffff
   #define A2W_PLLA_DIG1_WIDTH                                   24
   #define A2W_PLLA_DIG1_RESET                                   0000000000
#define A2W_PLLA_DIG2                                            HW_REGISTER_RW( 0x7e102008 ) 
   #define A2W_PLLA_DIG2_MASK                                    0x00ffffff
   #define A2W_PLLA_DIG2_WIDTH                                   24
   #define A2W_PLLA_DIG2_RESET                                   0000000000
#define A2W_PLLA_DIG3                                            HW_REGISTER_RW( 0x7e10200c ) 
   #define A2W_PLLA_DIG3_MASK                                    0x00ffffff
   #define A2W_PLLA_DIG3_WIDTH                                   24
   #define A2W_PLLA_DIG3_RESET                                   0000000000
#define A2W_PLLA_ANA0                                            HW_REGISTER_RW( 0x7e102010 ) 
   #define A2W_PLLA_ANA0_MASK                                    0x00ffffff
   #define A2W_PLLA_ANA0_WIDTH                                   24
   #define A2W_PLLA_ANA0_RESET                                   0000000000
#define A2W_PLLA_ANA1                                            HW_REGISTER_RW( 0x7e102014 ) 
   #define A2W_PLLA_ANA1_MASK                                    0x00ffffff
   #define A2W_PLLA_ANA1_WIDTH                                   24
   #define A2W_PLLA_ANA1_RESET                                   0000000000
#define A2W_PLLA_ANA2                                            HW_REGISTER_RW( 0x7e102018 ) 
   #define A2W_PLLA_ANA2_MASK                                    0x00ffffff
   #define A2W_PLLA_ANA2_WIDTH                                   24
   #define A2W_PLLA_ANA2_RESET                                   0000000000
#define A2W_PLLA_ANA3                                            HW_REGISTER_RW( 0x7e10201c ) 
   #define A2W_PLLA_ANA3_MASK                                    0x00ffffff
   #define A2W_PLLA_ANA3_WIDTH                                   24
   #define A2W_PLLA_ANA3_RESET                                   0000000000
#define A2W_PLLC_DIG0                                            HW_REGISTER_RW( 0x7e102020 ) 
   #define A2W_PLLC_DIG0_MASK                                    0x00ffffff
   #define A2W_PLLC_DIG0_WIDTH                                   24
   #define A2W_PLLC_DIG0_RESET                                   0000000000
#define A2W_PLLC_DIG1                                            HW_REGISTER_RW( 0x7e102024 ) 
   #define A2W_PLLC_DIG1_MASK                                    0x00ffffff
   #define A2W_PLLC_DIG1_WIDTH                                   24
   #define A2W_PLLC_DIG1_RESET                                   0000000000
#define A2W_PLLC_DIG2                                            HW_REGISTER_RW( 0x7e102028 ) 
   #define A2W_PLLC_DIG2_MASK                                    0x00ffffff
   #define A2W_PLLC_DIG2_WIDTH                                   24
   #define A2W_PLLC_DIG2_RESET                                   0000000000
#define A2W_PLLC_DIG3                                            HW_REGISTER_RW( 0x7e10202c ) 
   #define A2W_PLLC_DIG3_MASK                                    0x00ffffff
   #define A2W_PLLC_DIG3_WIDTH                                   24
   #define A2W_PLLC_DIG3_RESET                                   0000000000
#define A2W_PLLC_ANA0                                            HW_REGISTER_RW( 0x7e102030 ) 
   #define A2W_PLLC_ANA0_MASK                                    0x00ffffff
   #define A2W_PLLC_ANA0_WIDTH                                   24
   #define A2W_PLLC_ANA0_RESET                                   0000000000
#define A2W_PLLC_ANA1                                            HW_REGISTER_RW( 0x7e102034 ) 
   #define A2W_PLLC_ANA1_MASK                                    0x00ffffff
   #define A2W_PLLC_ANA1_WIDTH                                   24
   #define A2W_PLLC_ANA1_RESET                                   0000000000
#define A2W_PLLC_ANA2                                            HW_REGISTER_RW( 0x7e102038 ) 
   #define A2W_PLLC_ANA2_MASK                                    0x00ffffff
   #define A2W_PLLC_ANA2_WIDTH                                   24
   #define A2W_PLLC_ANA2_RESET                                   0000000000
#define A2W_PLLC_ANA3                                            HW_REGISTER_RW( 0x7e10203c ) 
   #define A2W_PLLC_ANA3_MASK                                    0x00ffffff
   #define A2W_PLLC_ANA3_WIDTH                                   24
   #define A2W_PLLC_ANA3_RESET                                   0000000000
#define A2W_PLLD_DIG0                                            HW_REGISTER_RW( 0x7e102040 ) 
   #define A2W_PLLD_DIG0_MASK                                    0x00ffffff
   #define A2W_PLLD_DIG0_WIDTH                                   24
   #define A2W_PLLD_DIG0_RESET                                   0000000000
#define A2W_PLLD_DIG1                                            HW_REGISTER_RW( 0x7e102044 ) 
   #define A2W_PLLD_DIG1_MASK                                    0x00ffffff
   #define A2W_PLLD_DIG1_WIDTH                                   24
   #define A2W_PLLD_DIG1_RESET                                   0000000000
#define A2W_PLLD_DIG2                                            HW_REGISTER_RW( 0x7e102048 ) 
   #define A2W_PLLD_DIG2_MASK                                    0x00ffffff
   #define A2W_PLLD_DIG2_WIDTH                                   24
   #define A2W_PLLD_DIG2_RESET                                   0000000000
#define A2W_PLLD_DIG3                                            HW_REGISTER_RW( 0x7e10204c ) 
   #define A2W_PLLD_DIG3_MASK                                    0x00ffffff
   #define A2W_PLLD_DIG3_WIDTH                                   24
   #define A2W_PLLD_DIG3_RESET                                   0000000000
#define A2W_PLLD_ANA0                                            HW_REGISTER_RW( 0x7e102050 ) 
   #define A2W_PLLD_ANA0_MASK                                    0x00ffffff
   #define A2W_PLLD_ANA0_WIDTH                                   24
   #define A2W_PLLD_ANA0_RESET                                   0000000000
#define A2W_PLLD_ANA1                                            HW_REGISTER_RW( 0x7e102054 ) 
   #define A2W_PLLD_ANA1_MASK                                    0x00ffffff
   #define A2W_PLLD_ANA1_WIDTH                                   24
   #define A2W_PLLD_ANA1_RESET                                   0000000000
#define A2W_PLLD_ANA2                                            HW_REGISTER_RW( 0x7e102058 ) 
   #define A2W_PLLD_ANA2_MASK                                    0x00ffffff
   #define A2W_PLLD_ANA2_WIDTH                                   24
   #define A2W_PLLD_ANA2_RESET                                   0000000000
#define A2W_PLLD_ANA3                                            HW_REGISTER_RW( 0x7e10205c ) 
   #define A2W_PLLD_ANA3_MASK                                    0x00ffffff
   #define A2W_PLLD_ANA3_WIDTH                                   24
   #define A2W_PLLD_ANA3_RESET                                   0000000000
#define A2W_PLLH_DIG0                                            HW_REGISTER_RW( 0x7e102060 ) 
   #define A2W_PLLH_DIG0_MASK                                    0x00ffffff
   #define A2W_PLLH_DIG0_WIDTH                                   24
   #define A2W_PLLH_DIG0_RESET                                   0000000000
#define A2W_PLLH_DIG1                                            HW_REGISTER_RW( 0x7e102064 ) 
   #define A2W_PLLH_DIG1_MASK                                    0x00ffffff
   #define A2W_PLLH_DIG1_WIDTH                                   24
   #define A2W_PLLH_DIG1_RESET                                   0000000000
#define A2W_PLLH_DIG2                                            HW_REGISTER_RW( 0x7e102068 ) 
   #define A2W_PLLH_DIG2_MASK                                    0x00ffffff
   #define A2W_PLLH_DIG2_WIDTH                                   24
   #define A2W_PLLH_DIG2_RESET                                   0000000000
#define A2W_PLLH_DIG3                                            HW_REGISTER_RW( 0x7e10206c ) 
   #define A2W_PLLH_DIG3_MASK                                    0x00ffffff
   #define A2W_PLLH_DIG3_WIDTH                                   24
   #define A2W_PLLH_DIG3_RESET                                   0000000000
#define A2W_PLLH_ANA0                                            HW_REGISTER_RW( 0x7e102070 ) 
   #define A2W_PLLH_ANA0_MASK                                    0x00ffffff
   #define A2W_PLLH_ANA0_WIDTH                                   24
   #define A2W_PLLH_ANA0_RESET                                   0000000000
#define A2W_PLLH_ANA1                                            HW_REGISTER_RW( 0x7e102074 ) 
   #define A2W_PLLH_ANA1_MASK                                    0x00ffffff
   #define A2W_PLLH_ANA1_WIDTH                                   24
   #define A2W_PLLH_ANA1_RESET                                   0000000000
#define A2W_PLLH_ANA2                                            HW_REGISTER_RW( 0x7e102078 ) 
   #define A2W_PLLH_ANA2_MASK                                    0x00ffffff
   #define A2W_PLLH_ANA2_WIDTH                                   24
   #define A2W_PLLH_ANA2_RESET                                   0000000000
#define A2W_PLLH_ANA3                                            HW_REGISTER_RW( 0x7e10207c ) 
   #define A2W_PLLH_ANA3_MASK                                    0x00ffffff
   #define A2W_PLLH_ANA3_WIDTH                                   24
   #define A2W_PLLH_ANA3_RESET                                   0000000000
#define A2W_HDMI_CTL0                                            HW_REGISTER_RW( 0x7e102080 ) 
   #define A2W_HDMI_CTL0_MASK                                    0x00ffffff
   #define A2W_HDMI_CTL0_WIDTH                                   24
   #define A2W_HDMI_CTL0_RESET                                   0000000000
#define A2W_HDMI_CTL1                                            HW_REGISTER_RW( 0x7e102084 ) 
   #define A2W_HDMI_CTL1_MASK                                    0x00ffffff
   #define A2W_HDMI_CTL1_WIDTH                                   24
   #define A2W_HDMI_CTL1_RESET                                   0000000000
#define A2W_HDMI_CTL2                                            HW_REGISTER_RW( 0x7e102088 ) 
   #define A2W_HDMI_CTL2_MASK                                    0x00ffffff
   #define A2W_HDMI_CTL2_WIDTH                                   24
   #define A2W_HDMI_CTL2_RESET                                   0000000000
#define A2W_HDMI_CTL3                                            HW_REGISTER_RW( 0x7e10208c ) 
   #define A2W_HDMI_CTL3_MASK                                    0x00ffffff
   #define A2W_HDMI_CTL3_WIDTH                                   24
   #define A2W_HDMI_CTL3_RESET                                   0000000000
#define A2W_XOSC0                                                HW_REGISTER_RW( 0x7e102090 ) 
   #define A2W_XOSC0_MASK                                        0x00ffffff
   #define A2W_XOSC0_WIDTH                                       24
   #define A2W_XOSC0_RESET                                       0000000000
#define A2W_XOSC1                                                HW_REGISTER_RW( 0x7e102094 ) 
   #define A2W_XOSC1_MASK                                        0x00ffffff
   #define A2W_XOSC1_WIDTH                                       24
   #define A2W_XOSC1_RESET                                       0000000000
#define A2W_SMPS_CTLA0                                           HW_REGISTER_RW( 0x7e1020a0 ) 
   #define A2W_SMPS_CTLA0_MASK                                   0x00ffffff
   #define A2W_SMPS_CTLA0_WIDTH                                  24
   #define A2W_SMPS_CTLA0_RESET                                  0000000000
#define A2W_SMPS_CTLA1                                           HW_REGISTER_RW( 0x7e1020a4 ) 
   #define A2W_SMPS_CTLA1_MASK                                   0x00ffffff
   #define A2W_SMPS_CTLA1_WIDTH                                  24
   #define A2W_SMPS_CTLA1_RESET                                  0000000000
#define A2W_SMPS_CTLA2                                           HW_REGISTER_RW( 0x7e1020a8 ) 
   #define A2W_SMPS_CTLA2_MASK                                   0x00ffffff
   #define A2W_SMPS_CTLA2_WIDTH                                  24
   #define A2W_SMPS_CTLA2_RESET                                  0000000000
#define A2W_SMPS_CTLB0                                           HW_REGISTER_RW( 0x7e1020b0 ) 
   #define A2W_SMPS_CTLB0_MASK                                   0x00ffffff
   #define A2W_SMPS_CTLB0_WIDTH                                  24
   #define A2W_SMPS_CTLB0_RESET                                  0000000000
#define A2W_SMPS_CTLB1                                           HW_REGISTER_RW( 0x7e1020b4 ) 
   #define A2W_SMPS_CTLB1_MASK                                   0x00ffffff
   #define A2W_SMPS_CTLB1_WIDTH                                  24
   #define A2W_SMPS_CTLB1_RESET                                  0000000000
#define A2W_SMPS_CTLB2                                           HW_REGISTER_RW( 0x7e1020b8 ) 
   #define A2W_SMPS_CTLB2_MASK                                   0x00ffffff
   #define A2W_SMPS_CTLB2_WIDTH                                  24
   #define A2W_SMPS_CTLB2_RESET                                  0000000000
#define A2W_SMPS_CTLC0                                           HW_REGISTER_RW( 0x7e1020c0 ) 
   #define A2W_SMPS_CTLC0_MASK                                   0x00ffffff
   #define A2W_SMPS_CTLC0_WIDTH                                  24
   #define A2W_SMPS_CTLC0_RESET                                  0000000000
#define A2W_SMPS_CTLC1                                           HW_REGISTER_RW( 0x7e1020c4 ) 
   #define A2W_SMPS_CTLC1_MASK                                   0x00ffffff
   #define A2W_SMPS_CTLC1_WIDTH                                  24
   #define A2W_SMPS_CTLC1_RESET                                  0000000000
#define A2W_SMPS_CTLC2                                           HW_REGISTER_RW( 0x7e1020c8 ) 
   #define A2W_SMPS_CTLC2_MASK                                   0x00ffffff
   #define A2W_SMPS_CTLC2_WIDTH                                  24
   #define A2W_SMPS_CTLC2_RESET                                  0000000000
#define A2W_SMPS_CTLC3                                           HW_REGISTER_RW( 0x7e1020cc ) 
   #define A2W_SMPS_CTLC3_MASK                                   0x00ffffff
   #define A2W_SMPS_CTLC3_WIDTH                                  24
   #define A2W_SMPS_CTLC3_RESET                                  0000000000
#define A2W_SMPS_LDO0                                            HW_REGISTER_RW( 0x7e1020d0 ) 
   #define A2W_SMPS_LDO0_MASK                                    0x00ffffff
   #define A2W_SMPS_LDO0_WIDTH                                   24
   #define A2W_SMPS_LDO0_RESET                                   0000000000
#define A2W_SMPS_LDO1                                            HW_REGISTER_RW( 0x7e1020d4 ) 
   #define A2W_SMPS_LDO1_MASK                                    0x00ffffff
   #define A2W_SMPS_LDO1_WIDTH                                   24
   #define A2W_SMPS_LDO1_RESET                                   0000000000
#define A2W_PLLA_CTRL                                            HW_REGISTER_RW( 0x7e102100 ) 
   #define A2W_PLLA_CTRL_MASK                                    0x000373ff
   #define A2W_PLLA_CTRL_WIDTH                                   18
   #define A2W_PLLA_CTRL_RESET                                   0000000000
      #define A2W_PLLA_CTRL_PRSTN_BITS                           17:17
      #define A2W_PLLA_CTRL_PRSTN_SET                            0x00020000
      #define A2W_PLLA_CTRL_PRSTN_CLR                            0xfffdffff
      #define A2W_PLLA_CTRL_PRSTN_MSB                            17
      #define A2W_PLLA_CTRL_PRSTN_LSB                            17
      #define A2W_PLLA_CTRL_PWRDN_BITS                           16:16
      #define A2W_PLLA_CTRL_PWRDN_SET                            0x00010000
      #define A2W_PLLA_CTRL_PWRDN_CLR                            0xfffeffff
      #define A2W_PLLA_CTRL_PWRDN_MSB                            16
      #define A2W_PLLA_CTRL_PWRDN_LSB                            16
      #define A2W_PLLA_CTRL_PDIV_BITS                            14:12
      #define A2W_PLLA_CTRL_PDIV_SET                             0x00007000
      #define A2W_PLLA_CTRL_PDIV_CLR                             0xffff8fff
      #define A2W_PLLA_CTRL_PDIV_MSB                             14
      #define A2W_PLLA_CTRL_PDIV_LSB                             12
      #define A2W_PLLA_CTRL_NDIV_BITS                            9:0
      #define A2W_PLLA_CTRL_NDIV_SET                             0x000003ff
      #define A2W_PLLA_CTRL_NDIV_CLR                             0xfffffc00
      #define A2W_PLLA_CTRL_NDIV_MSB                             9
      #define A2W_PLLA_CTRL_NDIV_LSB                             0
#define A2W_PLLA_FRAC                                            HW_REGISTER_RW( 0x7e102200 ) 
   #define A2W_PLLA_FRAC_MASK                                    0x000fffff
   #define A2W_PLLA_FRAC_WIDTH                                   20
   #define A2W_PLLA_FRAC_RESET                                   0000000000
      #define A2W_PLLA_FRAC_FRAC_BITS                            19:0
      #define A2W_PLLA_FRAC_FRAC_SET                             0x000fffff
      #define A2W_PLLA_FRAC_FRAC_CLR                             0xfff00000
      #define A2W_PLLA_FRAC_FRAC_MSB                             19
      #define A2W_PLLA_FRAC_FRAC_LSB                             0
#define A2W_PLLA_DSI0                                            HW_REGISTER_RW( 0x7e102300 ) 
   #define A2W_PLLA_DSI0_MASK                                    0x000003ff
   #define A2W_PLLA_DSI0_WIDTH                                   10
   #define A2W_PLLA_DSI0_RESET                                   0000000000
      #define A2W_PLLA_DSI0_BYPEN_BITS                           9:9
      #define A2W_PLLA_DSI0_BYPEN_SET                            0x00000200
      #define A2W_PLLA_DSI0_BYPEN_CLR                            0xfffffdff
      #define A2W_PLLA_DSI0_BYPEN_MSB                            9
      #define A2W_PLLA_DSI0_BYPEN_LSB                            9
      #define A2W_PLLA_DSI0_CHENB_BITS                           8:8
      #define A2W_PLLA_DSI0_CHENB_SET                            0x00000100
      #define A2W_PLLA_DSI0_CHENB_CLR                            0xfffffeff
      #define A2W_PLLA_DSI0_CHENB_MSB                            8
      #define A2W_PLLA_DSI0_CHENB_LSB                            8
      #define A2W_PLLA_DSI0_DIV_BITS                             7:0
      #define A2W_PLLA_DSI0_DIV_SET                              0x000000ff
      #define A2W_PLLA_DSI0_DIV_CLR                              0xffffff00
      #define A2W_PLLA_DSI0_DIV_MSB                              7
      #define A2W_PLLA_DSI0_DIV_LSB                              0
#define A2W_PLLA_CORE                                            HW_REGISTER_RW( 0x7e102400 ) 
   #define A2W_PLLA_CORE_MASK                                    0x000003ff
   #define A2W_PLLA_CORE_WIDTH                                   10
   #define A2W_PLLA_CORE_RESET                                   0000000000
      #define A2W_PLLA_CORE_BYPEN_BITS                           9:9
      #define A2W_PLLA_CORE_BYPEN_SET                            0x00000200
      #define A2W_PLLA_CORE_BYPEN_CLR                            0xfffffdff
      #define A2W_PLLA_CORE_BYPEN_MSB                            9
      #define A2W_PLLA_CORE_BYPEN_LSB                            9
      #define A2W_PLLA_CORE_CHENB_BITS                           8:8
      #define A2W_PLLA_CORE_CHENB_SET                            0x00000100
      #define A2W_PLLA_CORE_CHENB_CLR                            0xfffffeff
      #define A2W_PLLA_CORE_CHENB_MSB                            8
      #define A2W_PLLA_CORE_CHENB_LSB                            8
      #define A2W_PLLA_CORE_DIV_BITS                             7:0
      #define A2W_PLLA_CORE_DIV_SET                              0x000000ff
      #define A2W_PLLA_CORE_DIV_CLR                              0xffffff00
      #define A2W_PLLA_CORE_DIV_MSB                              7
      #define A2W_PLLA_CORE_DIV_LSB                              0
#define A2W_PLLA_PER                                             HW_REGISTER_RW( 0x7e102500 ) 
   #define A2W_PLLA_PER_MASK                                     0x000003ff
   #define A2W_PLLA_PER_WIDTH                                    10
   #define A2W_PLLA_PER_RESET                                    0000000000
      #define A2W_PLLA_PER_BYPEN_BITS                            9:9
      #define A2W_PLLA_PER_BYPEN_SET                             0x00000200
      #define A2W_PLLA_PER_BYPEN_CLR                             0xfffffdff
      #define A2W_PLLA_PER_BYPEN_MSB                             9
      #define A2W_PLLA_PER_BYPEN_LSB                             9
      #define A2W_PLLA_PER_CHENB_BITS                            8:8
      #define A2W_PLLA_PER_CHENB_SET                             0x00000100
      #define A2W_PLLA_PER_CHENB_CLR                             0xfffffeff
      #define A2W_PLLA_PER_CHENB_MSB                             8
      #define A2W_PLLA_PER_CHENB_LSB                             8
      #define A2W_PLLA_PER_DIV_BITS                              7:0
      #define A2W_PLLA_PER_DIV_SET                               0x000000ff
      #define A2W_PLLA_PER_DIV_CLR                               0xffffff00
      #define A2W_PLLA_PER_DIV_MSB                               7
      #define A2W_PLLA_PER_DIV_LSB                               0
#define A2W_PLLA_CCP2                                            HW_REGISTER_RW( 0x7e102600 ) 
   #define A2W_PLLA_CCP2_MASK                                    0x000003ff
   #define A2W_PLLA_CCP2_WIDTH                                   10
   #define A2W_PLLA_CCP2_RESET                                   0000000000
      #define A2W_PLLA_CCP2_BYPEN_BITS                           9:9
      #define A2W_PLLA_CCP2_BYPEN_SET                            0x00000200
      #define A2W_PLLA_CCP2_BYPEN_CLR                            0xfffffdff
      #define A2W_PLLA_CCP2_BYPEN_MSB                            9
      #define A2W_PLLA_CCP2_BYPEN_LSB                            9
      #define A2W_PLLA_CCP2_CHENB_BITS                           8:8
      #define A2W_PLLA_CCP2_CHENB_SET                            0x00000100
      #define A2W_PLLA_CCP2_CHENB_CLR                            0xfffffeff
      #define A2W_PLLA_CCP2_CHENB_MSB                            8
      #define A2W_PLLA_CCP2_CHENB_LSB                            8
      #define A2W_PLLA_CCP2_DIV_BITS                             7:0
      #define A2W_PLLA_CCP2_DIV_SET                              0x000000ff
      #define A2W_PLLA_CCP2_DIV_CLR                              0xffffff00
      #define A2W_PLLA_CCP2_DIV_MSB                              7
      #define A2W_PLLA_CCP2_DIV_LSB                              0
#define A2W_PLLC_CTRL                                            HW_REGISTER_RW( 0x7e102120 ) 
   #define A2W_PLLC_CTRL_MASK                                    0x000373ff
   #define A2W_PLLC_CTRL_WIDTH                                   18
   #define A2W_PLLC_CTRL_RESET                                   0000000000
      #define A2W_PLLC_CTRL_PRSTN_BITS                           17:17
      #define A2W_PLLC_CTRL_PRSTN_SET                            0x00020000
      #define A2W_PLLC_CTRL_PRSTN_CLR                            0xfffdffff
      #define A2W_PLLC_CTRL_PRSTN_MSB                            17
      #define A2W_PLLC_CTRL_PRSTN_LSB                            17
      #define A2W_PLLC_CTRL_PWRDN_BITS                           16:16
      #define A2W_PLLC_CTRL_PWRDN_SET                            0x00010000
      #define A2W_PLLC_CTRL_PWRDN_CLR                            0xfffeffff
      #define A2W_PLLC_CTRL_PWRDN_MSB                            16
      #define A2W_PLLC_CTRL_PWRDN_LSB                            16
      #define A2W_PLLC_CTRL_PDIV_BITS                            14:12
      #define A2W_PLLC_CTRL_PDIV_SET                             0x00007000
      #define A2W_PLLC_CTRL_PDIV_CLR                             0xffff8fff
      #define A2W_PLLC_CTRL_PDIV_MSB                             14
      #define A2W_PLLC_CTRL_PDIV_LSB                             12
      #define A2W_PLLC_CTRL_NDIV_BITS                            9:0
      #define A2W_PLLC_CTRL_NDIV_SET                             0x000003ff
      #define A2W_PLLC_CTRL_NDIV_CLR                             0xfffffc00
      #define A2W_PLLC_CTRL_NDIV_MSB                             9
      #define A2W_PLLC_CTRL_NDIV_LSB                             0
#define A2W_PLLC_FRAC                                            HW_REGISTER_RW( 0x7e102220 ) 
   #define A2W_PLLC_FRAC_MASK                                    0x000fffff
   #define A2W_PLLC_FRAC_WIDTH                                   20
   #define A2W_PLLC_FRAC_RESET                                   0000000000
      #define A2W_PLLC_FRAC_FRAC_BITS                            19:0
      #define A2W_PLLC_FRAC_FRAC_SET                             0x000fffff
      #define A2W_PLLC_FRAC_FRAC_CLR                             0xfff00000
      #define A2W_PLLC_FRAC_FRAC_MSB                             19
      #define A2W_PLLC_FRAC_FRAC_LSB                             0
#define A2W_PLLC_CORE2                                           HW_REGISTER_RW( 0x7e102320 ) 
   #define A2W_PLLC_CORE2_MASK                                   0x000003ff
   #define A2W_PLLC_CORE2_WIDTH                                  10
   #define A2W_PLLC_CORE2_RESET                                  0000000000
      #define A2W_PLLC_CORE2_BYPEN_BITS                          9:9
      #define A2W_PLLC_CORE2_BYPEN_SET                           0x00000200
      #define A2W_PLLC_CORE2_BYPEN_CLR                           0xfffffdff
      #define A2W_PLLC_CORE2_BYPEN_MSB                           9
      #define A2W_PLLC_CORE2_BYPEN_LSB                           9
      #define A2W_PLLC_CORE2_CHENB_BITS                          8:8
      #define A2W_PLLC_CORE2_CHENB_SET                           0x00000100
      #define A2W_PLLC_CORE2_CHENB_CLR                           0xfffffeff
      #define A2W_PLLC_CORE2_CHENB_MSB                           8
      #define A2W_PLLC_CORE2_CHENB_LSB                           8
      #define A2W_PLLC_CORE2_DIV_BITS                            7:0
      #define A2W_PLLC_CORE2_DIV_SET                             0x000000ff
      #define A2W_PLLC_CORE2_DIV_CLR                             0xffffff00
      #define A2W_PLLC_CORE2_DIV_MSB                             7
      #define A2W_PLLC_CORE2_DIV_LSB                             0
#define A2W_PLLC_CORE1                                           HW_REGISTER_RW( 0x7e102420 ) 
   #define A2W_PLLC_CORE1_MASK                                   0x000003ff
   #define A2W_PLLC_CORE1_WIDTH                                  10
   #define A2W_PLLC_CORE1_RESET                                  0000000000
      #define A2W_PLLC_CORE1_BYPEN_BITS                          9:9
      #define A2W_PLLC_CORE1_BYPEN_SET                           0x00000200
      #define A2W_PLLC_CORE1_BYPEN_CLR                           0xfffffdff
      #define A2W_PLLC_CORE1_BYPEN_MSB                           9
      #define A2W_PLLC_CORE1_BYPEN_LSB                           9
      #define A2W_PLLC_CORE1_CHENB_BITS                          8:8
      #define A2W_PLLC_CORE1_CHENB_SET                           0x00000100
      #define A2W_PLLC_CORE1_CHENB_CLR                           0xfffffeff
      #define A2W_PLLC_CORE1_CHENB_MSB                           8
      #define A2W_PLLC_CORE1_CHENB_LSB                           8
      #define A2W_PLLC_CORE1_DIV_BITS                            7:0
      #define A2W_PLLC_CORE1_DIV_SET                             0x000000ff
      #define A2W_PLLC_CORE1_DIV_CLR                             0xffffff00
      #define A2W_PLLC_CORE1_DIV_MSB                             7
      #define A2W_PLLC_CORE1_DIV_LSB                             0
#define A2W_PLLC_PER                                             HW_REGISTER_RW( 0x7e102520 ) 
   #define A2W_PLLC_PER_MASK                                     0x000003ff
   #define A2W_PLLC_PER_WIDTH                                    10
   #define A2W_PLLC_PER_RESET                                    0000000000
      #define A2W_PLLC_PER_BYPEN_BITS                            9:9
      #define A2W_PLLC_PER_BYPEN_SET                             0x00000200
      #define A2W_PLLC_PER_BYPEN_CLR                             0xfffffdff
      #define A2W_PLLC_PER_BYPEN_MSB                             9
      #define A2W_PLLC_PER_BYPEN_LSB                             9
      #define A2W_PLLC_PER_CHENB_BITS                            8:8
      #define A2W_PLLC_PER_CHENB_SET                             0x00000100
      #define A2W_PLLC_PER_CHENB_CLR                             0xfffffeff
      #define A2W_PLLC_PER_CHENB_MSB                             8
      #define A2W_PLLC_PER_CHENB_LSB                             8
      #define A2W_PLLC_PER_DIV_BITS                              7:0
      #define A2W_PLLC_PER_DIV_SET                               0x000000ff
      #define A2W_PLLC_PER_DIV_CLR                               0xffffff00
      #define A2W_PLLC_PER_DIV_MSB                               7
      #define A2W_PLLC_PER_DIV_LSB                               0
#define A2W_PLLC_CORE0                                           HW_REGISTER_RW( 0x7e102620 ) 
   #define A2W_PLLC_CORE0_MASK                                   0x000003ff
   #define A2W_PLLC_CORE0_WIDTH                                  10
   #define A2W_PLLC_CORE0_RESET                                  0000000000
      #define A2W_PLLC_CORE0_BYPEN_BITS                          9:9
      #define A2W_PLLC_CORE0_BYPEN_SET                           0x00000200
      #define A2W_PLLC_CORE0_BYPEN_CLR                           0xfffffdff
      #define A2W_PLLC_CORE0_BYPEN_MSB                           9
      #define A2W_PLLC_CORE0_BYPEN_LSB                           9
      #define A2W_PLLC_CORE0_CHENB_BITS                          8:8
      #define A2W_PLLC_CORE0_CHENB_SET                           0x00000100
      #define A2W_PLLC_CORE0_CHENB_CLR                           0xfffffeff
      #define A2W_PLLC_CORE0_CHENB_MSB                           8
      #define A2W_PLLC_CORE0_CHENB_LSB                           8
      #define A2W_PLLC_CORE0_DIV_BITS                            7:0
      #define A2W_PLLC_CORE0_DIV_SET                             0x000000ff
      #define A2W_PLLC_CORE0_DIV_CLR                             0xffffff00
      #define A2W_PLLC_CORE0_DIV_MSB                             7
      #define A2W_PLLC_CORE0_DIV_LSB                             0
#define A2W_PLLD_CTRL                                            HW_REGISTER_RW( 0x7e102140 ) 
   #define A2W_PLLD_CTRL_MASK                                    0x000373ff
   #define A2W_PLLD_CTRL_WIDTH                                   18
   #define A2W_PLLD_CTRL_RESET                                   0000000000
      #define A2W_PLLD_CTRL_PRSTN_BITS                           17:17
      #define A2W_PLLD_CTRL_PRSTN_SET                            0x00020000
      #define A2W_PLLD_CTRL_PRSTN_CLR                            0xfffdffff
      #define A2W_PLLD_CTRL_PRSTN_MSB                            17
      #define A2W_PLLD_CTRL_PRSTN_LSB                            17
      #define A2W_PLLD_CTRL_PWRDN_BITS                           16:16
      #define A2W_PLLD_CTRL_PWRDN_SET                            0x00010000
      #define A2W_PLLD_CTRL_PWRDN_CLR                            0xfffeffff
      #define A2W_PLLD_CTRL_PWRDN_MSB                            16
      #define A2W_PLLD_CTRL_PWRDN_LSB                            16
      #define A2W_PLLD_CTRL_PDIV_BITS                            14:12
      #define A2W_PLLD_CTRL_PDIV_SET                             0x00007000
      #define A2W_PLLD_CTRL_PDIV_CLR                             0xffff8fff
      #define A2W_PLLD_CTRL_PDIV_MSB                             14
      #define A2W_PLLD_CTRL_PDIV_LSB                             12
      #define A2W_PLLD_CTRL_NDIV_BITS                            9:0
      #define A2W_PLLD_CTRL_NDIV_SET                             0x000003ff
      #define A2W_PLLD_CTRL_NDIV_CLR                             0xfffffc00
      #define A2W_PLLD_CTRL_NDIV_MSB                             9
      #define A2W_PLLD_CTRL_NDIV_LSB                             0
#define A2W_PLLD_FRAC                                            HW_REGISTER_RW( 0x7e102240 ) 
   #define A2W_PLLD_FRAC_MASK                                    0x000fffff
   #define A2W_PLLD_FRAC_WIDTH                                   20
   #define A2W_PLLD_FRAC_RESET                                   0000000000
      #define A2W_PLLD_FRAC_FRAC_BITS                            19:0
      #define A2W_PLLD_FRAC_FRAC_SET                             0x000fffff
      #define A2W_PLLD_FRAC_FRAC_CLR                             0xfff00000
      #define A2W_PLLD_FRAC_FRAC_MSB                             19
      #define A2W_PLLD_FRAC_FRAC_LSB                             0
#define A2W_PLLD_DSI0                                            HW_REGISTER_RW( 0x7e102340 ) 
   #define A2W_PLLD_DSI0_MASK                                    0x000003ff
   #define A2W_PLLD_DSI0_WIDTH                                   10
   #define A2W_PLLD_DSI0_RESET                                   0000000000
      #define A2W_PLLD_DSI0_BYPEN_BITS                           9:9
      #define A2W_PLLD_DSI0_BYPEN_SET                            0x00000200
      #define A2W_PLLD_DSI0_BYPEN_CLR                            0xfffffdff
      #define A2W_PLLD_DSI0_BYPEN_MSB                            9
      #define A2W_PLLD_DSI0_BYPEN_LSB                            9
      #define A2W_PLLD_DSI0_CHENB_BITS                           8:8
      #define A2W_PLLD_DSI0_CHENB_SET                            0x00000100
      #define A2W_PLLD_DSI0_CHENB_CLR                            0xfffffeff
      #define A2W_PLLD_DSI0_CHENB_MSB                            8
      #define A2W_PLLD_DSI0_CHENB_LSB                            8
      #define A2W_PLLD_DSI0_DIV_BITS                             7:0
      #define A2W_PLLD_DSI0_DIV_SET                              0x000000ff
      #define A2W_PLLD_DSI0_DIV_CLR                              0xffffff00
      #define A2W_PLLD_DSI0_DIV_MSB                              7
      #define A2W_PLLD_DSI0_DIV_LSB                              0
#define A2W_PLLD_CORE                                            HW_REGISTER_RW( 0x7e102440 ) 
   #define A2W_PLLD_CORE_MASK                                    0x000003ff
   #define A2W_PLLD_CORE_WIDTH                                   10
   #define A2W_PLLD_CORE_RESET                                   0000000000
      #define A2W_PLLD_CORE_BYPEN_BITS                           9:9
      #define A2W_PLLD_CORE_BYPEN_SET                            0x00000200
      #define A2W_PLLD_CORE_BYPEN_CLR                            0xfffffdff
      #define A2W_PLLD_CORE_BYPEN_MSB                            9
      #define A2W_PLLD_CORE_BYPEN_LSB                            9
      #define A2W_PLLD_CORE_CHENB_BITS                           8:8
      #define A2W_PLLD_CORE_CHENB_SET                            0x00000100
      #define A2W_PLLD_CORE_CHENB_CLR                            0xfffffeff
      #define A2W_PLLD_CORE_CHENB_MSB                            8
      #define A2W_PLLD_CORE_CHENB_LSB                            8
      #define A2W_PLLD_CORE_DIV_BITS                             7:0
      #define A2W_PLLD_CORE_DIV_SET                              0x000000ff
      #define A2W_PLLD_CORE_DIV_CLR                              0xffffff00
      #define A2W_PLLD_CORE_DIV_MSB                              7
      #define A2W_PLLD_CORE_DIV_LSB                              0
#define A2W_PLLD_PER                                             HW_REGISTER_RW( 0x7e102540 ) 
   #define A2W_PLLD_PER_MASK                                     0x000003ff
   #define A2W_PLLD_PER_WIDTH                                    10
   #define A2W_PLLD_PER_RESET                                    0000000000
      #define A2W_PLLD_PER_BYPEN_BITS                            9:9
      #define A2W_PLLD_PER_BYPEN_SET                             0x00000200
      #define A2W_PLLD_PER_BYPEN_CLR                             0xfffffdff
      #define A2W_PLLD_PER_BYPEN_MSB                             9
      #define A2W_PLLD_PER_BYPEN_LSB                             9
      #define A2W_PLLD_PER_CHENB_BITS                            8:8
      #define A2W_PLLD_PER_CHENB_SET                             0x00000100
      #define A2W_PLLD_PER_CHENB_CLR                             0xfffffeff
      #define A2W_PLLD_PER_CHENB_MSB                             8
      #define A2W_PLLD_PER_CHENB_LSB                             8
      #define A2W_PLLD_PER_DIV_BITS                              7:0
      #define A2W_PLLD_PER_DIV_SET                               0x000000ff
      #define A2W_PLLD_PER_DIV_CLR                               0xffffff00
      #define A2W_PLLD_PER_DIV_MSB                               7
      #define A2W_PLLD_PER_DIV_LSB                               0
#define A2W_PLLD_DSI1                                            HW_REGISTER_RW( 0x7e102640 ) 
   #define A2W_PLLD_DSI1_MASK                                    0x000003ff
   #define A2W_PLLD_DSI1_WIDTH                                   10
   #define A2W_PLLD_DSI1_RESET                                   0000000000
      #define A2W_PLLD_DSI1_BYPEN_BITS                           9:9
      #define A2W_PLLD_DSI1_BYPEN_SET                            0x00000200
      #define A2W_PLLD_DSI1_BYPEN_CLR                            0xfffffdff
      #define A2W_PLLD_DSI1_BYPEN_MSB                            9
      #define A2W_PLLD_DSI1_BYPEN_LSB                            9
      #define A2W_PLLD_DSI1_CHENB_BITS                           8:8
      #define A2W_PLLD_DSI1_CHENB_SET                            0x00000100
      #define A2W_PLLD_DSI1_CHENB_CLR                            0xfffffeff
      #define A2W_PLLD_DSI1_CHENB_MSB                            8
      #define A2W_PLLD_DSI1_CHENB_LSB                            8
      #define A2W_PLLD_DSI1_DIV_BITS                             7:0
      #define A2W_PLLD_DSI1_DIV_SET                              0x000000ff
      #define A2W_PLLD_DSI1_DIV_CLR                              0xffffff00
      #define A2W_PLLD_DSI1_DIV_MSB                              7
      #define A2W_PLLD_DSI1_DIV_LSB                              0
#define A2W_PLLH_CTRL                                            HW_REGISTER_RW( 0x7e102160 ) 
   #define A2W_PLLH_CTRL_MASK                                    0x000370ff
   #define A2W_PLLH_CTRL_WIDTH                                   18
   #define A2W_PLLH_CTRL_RESET                                   0000000000
      #define A2W_PLLH_CTRL_PRSTN_BITS                           17:17
      #define A2W_PLLH_CTRL_PRSTN_SET                            0x00020000
      #define A2W_PLLH_CTRL_PRSTN_CLR                            0xfffdffff
      #define A2W_PLLH_CTRL_PRSTN_MSB                            17
      #define A2W_PLLH_CTRL_PRSTN_LSB                            17
      #define A2W_PLLH_CTRL_PWRDN_BITS                           16:16
      #define A2W_PLLH_CTRL_PWRDN_SET                            0x00010000
      #define A2W_PLLH_CTRL_PWRDN_CLR                            0xfffeffff
      #define A2W_PLLH_CTRL_PWRDN_MSB                            16
      #define A2W_PLLH_CTRL_PWRDN_LSB                            16
      #define A2W_PLLH_CTRL_PDIV_BITS                            14:12
      #define A2W_PLLH_CTRL_PDIV_SET                             0x00007000
      #define A2W_PLLH_CTRL_PDIV_CLR                             0xffff8fff
      #define A2W_PLLH_CTRL_PDIV_MSB                             14
      #define A2W_PLLH_CTRL_PDIV_LSB                             12
      #define A2W_PLLH_CTRL_NDIV_BITS                            7:0
      #define A2W_PLLH_CTRL_NDIV_SET                             0x000000ff
      #define A2W_PLLH_CTRL_NDIV_CLR                             0xffffff00
      #define A2W_PLLH_CTRL_NDIV_MSB                             7
      #define A2W_PLLH_CTRL_NDIV_LSB                             0
#define A2W_PLLH_FRAC                                            HW_REGISTER_RW( 0x7e102260 ) 
   #define A2W_PLLH_FRAC_MASK                                    0x000fffff
   #define A2W_PLLH_FRAC_WIDTH                                   20
   #define A2W_PLLH_FRAC_RESET                                   0000000000
      #define A2W_PLLH_FRAC_FRAC_BITS                            19:0
      #define A2W_PLLH_FRAC_FRAC_SET                             0x000fffff
      #define A2W_PLLH_FRAC_FRAC_CLR                             0xfff00000
      #define A2W_PLLH_FRAC_FRAC_MSB                             19
      #define A2W_PLLH_FRAC_FRAC_LSB                             0
#define A2W_PLLH_AUX                                             HW_REGISTER_RW( 0x7e102360 ) 
   #define A2W_PLLH_AUX_MASK                                     0x000003ff
   #define A2W_PLLH_AUX_WIDTH                                    10
   #define A2W_PLLH_AUX_RESET                                    0000000000
      #define A2W_PLLH_AUX_BYPEN_BITS                            9:9
      #define A2W_PLLH_AUX_BYPEN_SET                             0x00000200
      #define A2W_PLLH_AUX_BYPEN_CLR                             0xfffffdff
      #define A2W_PLLH_AUX_BYPEN_MSB                             9
      #define A2W_PLLH_AUX_BYPEN_LSB                             9
      #define A2W_PLLH_AUX_CHENB_BITS                            8:8
      #define A2W_PLLH_AUX_CHENB_SET                             0x00000100
      #define A2W_PLLH_AUX_CHENB_CLR                             0xfffffeff
      #define A2W_PLLH_AUX_CHENB_MSB                             8
      #define A2W_PLLH_AUX_CHENB_LSB                             8
      #define A2W_PLLH_AUX_DIV_BITS                              7:0
      #define A2W_PLLH_AUX_DIV_SET                               0x000000ff
      #define A2W_PLLH_AUX_DIV_CLR                               0xffffff00
      #define A2W_PLLH_AUX_DIV_MSB                               7
      #define A2W_PLLH_AUX_DIV_LSB                               0
#define A2W_PLLH_RCAL                                            HW_REGISTER_RW( 0x7e102460 ) 
   #define A2W_PLLH_RCAL_MASK                                    0x000003ff
   #define A2W_PLLH_RCAL_WIDTH                                   10
   #define A2W_PLLH_RCAL_RESET                                   0000000000
      #define A2W_PLLH_RCAL_BYPEN_BITS                           9:9
      #define A2W_PLLH_RCAL_BYPEN_SET                            0x00000200
      #define A2W_PLLH_RCAL_BYPEN_CLR                            0xfffffdff
      #define A2W_PLLH_RCAL_BYPEN_MSB                            9
      #define A2W_PLLH_RCAL_BYPEN_LSB                            9
      #define A2W_PLLH_RCAL_CHENB_BITS                           8:8
      #define A2W_PLLH_RCAL_CHENB_SET                            0x00000100
      #define A2W_PLLH_RCAL_CHENB_CLR                            0xfffffeff
      #define A2W_PLLH_RCAL_CHENB_MSB                            8
      #define A2W_PLLH_RCAL_CHENB_LSB                            8
      #define A2W_PLLH_RCAL_DIV_BITS                             7:0
      #define A2W_PLLH_RCAL_DIV_SET                              0x000000ff
      #define A2W_PLLH_RCAL_DIV_CLR                              0xffffff00
      #define A2W_PLLH_RCAL_DIV_MSB                              7
      #define A2W_PLLH_RCAL_DIV_LSB                              0
#define A2W_PLLH_PIX                                             HW_REGISTER_RW( 0x7e102560 ) 
   #define A2W_PLLH_PIX_MASK                                     0x000003ff
   #define A2W_PLLH_PIX_WIDTH                                    10
   #define A2W_PLLH_PIX_RESET                                    0000000000
      #define A2W_PLLH_PIX_BYPEN_BITS                            9:9
      #define A2W_PLLH_PIX_BYPEN_SET                             0x00000200
      #define A2W_PLLH_PIX_BYPEN_CLR                             0xfffffdff
      #define A2W_PLLH_PIX_BYPEN_MSB                             9
      #define A2W_PLLH_PIX_BYPEN_LSB                             9
      #define A2W_PLLH_PIX_CHENB_BITS                            8:8
      #define A2W_PLLH_PIX_CHENB_SET                             0x00000100
      #define A2W_PLLH_PIX_CHENB_CLR                             0xfffffeff
      #define A2W_PLLH_PIX_CHENB_MSB                             8
      #define A2W_PLLH_PIX_CHENB_LSB                             8
      #define A2W_PLLH_PIX_DIV_BITS                              7:0
      #define A2W_PLLH_PIX_DIV_SET                               0x000000ff
      #define A2W_PLLH_PIX_DIV_CLR                               0xffffff00
      #define A2W_PLLH_PIX_DIV_MSB                               7
      #define A2W_PLLH_PIX_DIV_LSB                               0
#define A2W_PLLH_STS                                             HW_REGISTER_RW( 0x7e102660 ) 
   #define A2W_PLLH_STS_MASK                                     0xffffffff
   #define A2W_PLLH_STS_WIDTH                                    32
   #define A2W_PLLH_STS_RESET                                    0000000000
#define A2W_XOSC_CTRL                                            HW_REGISTER_RW( 0x7e102190 ) 
   #define A2W_XOSC_CTRL_MASK                                    0x0000037f
   #define A2W_XOSC_CTRL_WIDTH                                   10
   #define A2W_XOSC_CTRL_RESET                                   0000000000
      #define A2W_XOSC_CTRL_DIV_BITS                             9:8
      #define A2W_XOSC_CTRL_DIV_SET                              0x00000300
      #define A2W_XOSC_CTRL_DIV_CLR                              0xfffffcff
      #define A2W_XOSC_CTRL_DIV_MSB                              9
      #define A2W_XOSC_CTRL_DIV_LSB                              8
      #define A2W_XOSC_CTRL_PLLAEN_BITS                          6:6
      #define A2W_XOSC_CTRL_PLLAEN_SET                           0x00000040
      #define A2W_XOSC_CTRL_PLLAEN_CLR                           0xffffffbf
      #define A2W_XOSC_CTRL_PLLAEN_MSB                           6
      #define A2W_XOSC_CTRL_PLLAEN_LSB                           6
      #define A2W_XOSC_CTRL_PLLDEN_BITS                          5:5
      #define A2W_XOSC_CTRL_PLLDEN_SET                           0x00000020
      #define A2W_XOSC_CTRL_PLLDEN_CLR                           0xffffffdf
      #define A2W_XOSC_CTRL_PLLDEN_MSB                           5
      #define A2W_XOSC_CTRL_PLLDEN_LSB                           5
      #define A2W_XOSC_CTRL_DDREN_BITS                           4:4
      #define A2W_XOSC_CTRL_DDREN_SET                            0x00000010
      #define A2W_XOSC_CTRL_DDREN_CLR                            0xffffffef
      #define A2W_XOSC_CTRL_DDREN_MSB                            4
      #define A2W_XOSC_CTRL_DDREN_LSB                            4
      #define A2W_XOSC_CTRL_CPR1EN_BITS                          3:3
      #define A2W_XOSC_CTRL_CPR1EN_SET                           0x00000008
      #define A2W_XOSC_CTRL_CPR1EN_CLR                           0xfffffff7
      #define A2W_XOSC_CTRL_CPR1EN_MSB                           3
      #define A2W_XOSC_CTRL_CPR1EN_LSB                           3
      #define A2W_XOSC_CTRL_USBEN_BITS                           2:2
      #define A2W_XOSC_CTRL_USBEN_SET                            0x00000004
      #define A2W_XOSC_CTRL_USBEN_CLR                            0xfffffffb
      #define A2W_XOSC_CTRL_USBEN_MSB                            2
      #define A2W_XOSC_CTRL_USBEN_LSB                            2
      #define A2W_XOSC_CTRL_HDMIEN_BITS                          1:1
      #define A2W_XOSC_CTRL_HDMIEN_SET                           0x00000002
      #define A2W_XOSC_CTRL_HDMIEN_CLR                           0xfffffffd
      #define A2W_XOSC_CTRL_HDMIEN_MSB                           1
      #define A2W_XOSC_CTRL_HDMIEN_LSB                           1
      #define A2W_XOSC_CTRL_PLLCEN_BITS                          0:0
      #define A2W_XOSC_CTRL_PLLCEN_SET                           0x00000001
      #define A2W_XOSC_CTRL_PLLCEN_CLR                           0xfffffffe
      #define A2W_XOSC_CTRL_PLLCEN_MSB                           0
      #define A2W_XOSC_CTRL_PLLCEN_LSB                           0
#define A2W_PLLA_DIG0R                                           HW_REGISTER_RW( 0x7e102800 ) 
   #define A2W_PLLA_DIG0R_MASK                                   0x00ffffff
   #define A2W_PLLA_DIG0R_WIDTH                                  24
   #define A2W_PLLA_DIG0R_RESET                                  0000000000
#define A2W_PLLA_DIG1R                                           HW_REGISTER_RW( 0x7e102804 ) 
   #define A2W_PLLA_DIG1R_MASK                                   0x00ffffff
   #define A2W_PLLA_DIG1R_WIDTH                                  24
   #define A2W_PLLA_DIG1R_RESET                                  0000000000
#define A2W_PLLA_DIG2R                                           HW_REGISTER_RW( 0x7e102808 ) 
   #define A2W_PLLA_DIG2R_MASK                                   0x00ffffff
   #define A2W_PLLA_DIG2R_WIDTH                                  24
   #define A2W_PLLA_DIG2R_RESET                                  0000000000
#define A2W_PLLA_DIG3R                                           HW_REGISTER_RW( 0x7e10280c ) 
   #define A2W_PLLA_DIG3R_MASK                                   0x00ffffff
   #define A2W_PLLA_DIG3R_WIDTH                                  24
   #define A2W_PLLA_DIG3R_RESET                                  0000000000
#define A2W_PLLA_ANA0R                                           HW_REGISTER_RW( 0x7e102810 ) 
   #define A2W_PLLA_ANA0R_MASK                                   0x00ffffff
   #define A2W_PLLA_ANA0R_WIDTH                                  24
   #define A2W_PLLA_ANA0R_RESET                                  0000000000
#define A2W_PLLA_ANA1R                                           HW_REGISTER_RW( 0x7e102814 ) 
   #define A2W_PLLA_ANA1R_MASK                                   0x00ffffff
   #define A2W_PLLA_ANA1R_WIDTH                                  24
   #define A2W_PLLA_ANA1R_RESET                                  0000000000
#define A2W_PLLA_ANA2R                                           HW_REGISTER_RW( 0x7e102818 ) 
   #define A2W_PLLA_ANA2R_MASK                                   0x00ffffff
   #define A2W_PLLA_ANA2R_WIDTH                                  24
   #define A2W_PLLA_ANA2R_RESET                                  0000000000
#define A2W_PLLA_ANA3R                                           HW_REGISTER_RW( 0x7e10281c ) 
   #define A2W_PLLA_ANA3R_MASK                                   0x00ffffff
   #define A2W_PLLA_ANA3R_WIDTH                                  24
   #define A2W_PLLA_ANA3R_RESET                                  0000000000
#define A2W_PLLC_DIG0R                                           HW_REGISTER_RW( 0x7e102820 ) 
   #define A2W_PLLC_DIG0R_MASK                                   0x00ffffff
   #define A2W_PLLC_DIG0R_WIDTH                                  24
   #define A2W_PLLC_DIG0R_RESET                                  0000000000
#define A2W_PLLC_DIG1R                                           HW_REGISTER_RW( 0x7e102824 ) 
   #define A2W_PLLC_DIG1R_MASK                                   0x00ffffff
   #define A2W_PLLC_DIG1R_WIDTH                                  24
   #define A2W_PLLC_DIG1R_RESET                                  0000000000
#define A2W_PLLC_DIG2R                                           HW_REGISTER_RW( 0x7e102828 ) 
   #define A2W_PLLC_DIG2R_MASK                                   0x00ffffff
   #define A2W_PLLC_DIG2R_WIDTH                                  24
   #define A2W_PLLC_DIG2R_RESET                                  0000000000
#define A2W_PLLC_DIG3R                                           HW_REGISTER_RW( 0x7e10282c ) 
   #define A2W_PLLC_DIG3R_MASK                                   0x00ffffff
   #define A2W_PLLC_DIG3R_WIDTH                                  24
   #define A2W_PLLC_DIG3R_RESET                                  0000000000
#define A2W_PLLC_ANA0R                                           HW_REGISTER_RW( 0x7e102830 ) 
   #define A2W_PLLC_ANA0R_MASK                                   0x00ffffff
   #define A2W_PLLC_ANA0R_WIDTH                                  24
   #define A2W_PLLC_ANA0R_RESET                                  0000000000
#define A2W_PLLC_ANA1R                                           HW_REGISTER_RW( 0x7e102834 ) 
   #define A2W_PLLC_ANA1R_MASK                                   0x00ffffff
   #define A2W_PLLC_ANA1R_WIDTH                                  24
   #define A2W_PLLC_ANA1R_RESET                                  0000000000
#define A2W_PLLC_ANA2R                                           HW_REGISTER_RW( 0x7e102838 ) 
   #define A2W_PLLC_ANA2R_MASK                                   0x00ffffff
   #define A2W_PLLC_ANA2R_WIDTH                                  24
   #define A2W_PLLC_ANA2R_RESET                                  0000000000
#define A2W_PLLC_ANA3R                                           HW_REGISTER_RW( 0x7e10283c ) 
   #define A2W_PLLC_ANA3R_MASK                                   0x00ffffff
   #define A2W_PLLC_ANA3R_WIDTH                                  24
   #define A2W_PLLC_ANA3R_RESET                                  0000000000
#define A2W_PLLD_DIG0R                                           HW_REGISTER_RW( 0x7e102840 ) 
   #define A2W_PLLD_DIG0R_MASK                                   0x00ffffff
   #define A2W_PLLD_DIG0R_WIDTH                                  24
   #define A2W_PLLD_DIG0R_RESET                                  0000000000
#define A2W_PLLD_DIG1R                                           HW_REGISTER_RW( 0x7e102844 ) 
   #define A2W_PLLD_DIG1R_MASK                                   0x00ffffff
   #define A2W_PLLD_DIG1R_WIDTH                                  24
   #define A2W_PLLD_DIG1R_RESET                                  0000000000
#define A2W_PLLD_DIG2R                                           HW_REGISTER_RW( 0x7e102848 ) 
   #define A2W_PLLD_DIG2R_MASK                                   0x00ffffff
   #define A2W_PLLD_DIG2R_WIDTH                                  24
   #define A2W_PLLD_DIG2R_RESET                                  0000000000
#define A2W_PLLD_DIG3R                                           HW_REGISTER_RW( 0x7e10284c ) 
   #define A2W_PLLD_DIG3R_MASK                                   0x00ffffff
   #define A2W_PLLD_DIG3R_WIDTH                                  24
   #define A2W_PLLD_DIG3R_RESET                                  0000000000
#define A2W_PLLD_ANA0R                                           HW_REGISTER_RW( 0x7e102850 ) 
   #define A2W_PLLD_ANA0R_MASK                                   0x00ffffff
   #define A2W_PLLD_ANA0R_WIDTH                                  24
   #define A2W_PLLD_ANA0R_RESET                                  0000000000
#define A2W_PLLD_ANA1R                                           HW_REGISTER_RW( 0x7e102854 ) 
   #define A2W_PLLD_ANA1R_MASK                                   0x00ffffff
   #define A2W_PLLD_ANA1R_WIDTH                                  24
   #define A2W_PLLD_ANA1R_RESET                                  0000000000
#define A2W_PLLD_ANA2R                                           HW_REGISTER_RW( 0x7e102858 ) 
   #define A2W_PLLD_ANA2R_MASK                                   0x00ffffff
   #define A2W_PLLD_ANA2R_WIDTH                                  24
   #define A2W_PLLD_ANA2R_RESET                                  0000000000
#define A2W_PLLD_ANA3R                                           HW_REGISTER_RW( 0x7e10285c ) 
   #define A2W_PLLD_ANA3R_MASK                                   0x00ffffff
   #define A2W_PLLD_ANA3R_WIDTH                                  24
   #define A2W_PLLD_ANA3R_RESET                                  0000000000
#define A2W_PLLH_DIG0R                                           HW_REGISTER_RW( 0x7e102860 ) 
   #define A2W_PLLH_DIG0R_MASK                                   0x00ffffff
   #define A2W_PLLH_DIG0R_WIDTH                                  24
   #define A2W_PLLH_DIG0R_RESET                                  0000000000
#define A2W_PLLH_DIG1R                                           HW_REGISTER_RW( 0x7e102864 ) 
   #define A2W_PLLH_DIG1R_MASK                                   0x00ffffff
   #define A2W_PLLH_DIG1R_WIDTH                                  24
   #define A2W_PLLH_DIG1R_RESET                                  0000000000
#define A2W_PLLH_DIG2R                                           HW_REGISTER_RW( 0x7e102868 ) 
   #define A2W_PLLH_DIG2R_MASK                                   0x00ffffff
   #define A2W_PLLH_DIG2R_WIDTH                                  24
   #define A2W_PLLH_DIG2R_RESET                                  0000000000
#define A2W_PLLH_DIG3R                                           HW_REGISTER_RW( 0x7e10286c ) 
   #define A2W_PLLH_DIG3R_MASK                                   0x00ffffff
   #define A2W_PLLH_DIG3R_WIDTH                                  24
   #define A2W_PLLH_DIG3R_RESET                                  0000000000
#define A2W_PLLH_ANA0R                                           HW_REGISTER_RW( 0x7e102870 ) 
   #define A2W_PLLH_ANA0R_MASK                                   0x00ffffff
   #define A2W_PLLH_ANA0R_WIDTH                                  24
   #define A2W_PLLH_ANA0R_RESET                                  0000000000
#define A2W_PLLH_ANA1R                                           HW_REGISTER_RW( 0x7e102874 ) 
   #define A2W_PLLH_ANA1R_MASK                                   0x00ffffff
   #define A2W_PLLH_ANA1R_WIDTH                                  24
   #define A2W_PLLH_ANA1R_RESET                                  0000000000
#define A2W_PLLH_ANA2R                                           HW_REGISTER_RW( 0x7e102878 ) 
   #define A2W_PLLH_ANA2R_MASK                                   0x00ffffff
   #define A2W_PLLH_ANA2R_WIDTH                                  24
   #define A2W_PLLH_ANA2R_RESET                                  0000000000
#define A2W_PLLH_ANA3R                                           HW_REGISTER_RW( 0x7e10287c ) 
   #define A2W_PLLH_ANA3R_MASK                                   0x00ffffff
   #define A2W_PLLH_ANA3R_WIDTH                                  24
   #define A2W_PLLH_ANA3R_RESET                                  0000000000
#define A2W_HDMI_CTL0R                                           HW_REGISTER_RW( 0x7e102880 ) 
   #define A2W_HDMI_CTL0R_MASK                                   0x00ffffff
   #define A2W_HDMI_CTL0R_WIDTH                                  24
   #define A2W_HDMI_CTL0R_RESET                                  0000000000
#define A2W_HDMI_CTL1R                                           HW_REGISTER_RW( 0x7e102884 ) 
   #define A2W_HDMI_CTL1R_MASK                                   0x00ffffff
   #define A2W_HDMI_CTL1R_WIDTH                                  24
   #define A2W_HDMI_CTL1R_RESET                                  0000000000
#define A2W_HDMI_CTL2R                                           HW_REGISTER_RW( 0x7e102888 ) 
   #define A2W_HDMI_CTL2R_MASK                                   0x00ffffff
   #define A2W_HDMI_CTL2R_WIDTH                                  24
   #define A2W_HDMI_CTL2R_RESET                                  0000000000
#define A2W_HDMI_CTL3R                                           HW_REGISTER_RW( 0x7e10288c ) 
   #define A2W_HDMI_CTL3R_MASK                                   0x00ffffff
   #define A2W_HDMI_CTL3R_WIDTH                                  24
   #define A2W_HDMI_CTL3R_RESET                                  0000000000
#define A2W_XOSC0R                                               HW_REGISTER_RW( 0x7e102890 ) 
   #define A2W_XOSC0R_MASK                                       0x00ffffff
   #define A2W_XOSC0R_WIDTH                                      24
   #define A2W_XOSC0R_RESET                                      0000000000
#define A2W_XOSC1R                                               HW_REGISTER_RW( 0x7e102894 ) 
   #define A2W_XOSC1R_MASK                                       0x00ffffff
   #define A2W_XOSC1R_WIDTH                                      24
   #define A2W_XOSC1R_RESET                                      0000000000
#define A2W_SMPS_CTLA0R                                          HW_REGISTER_RW( 0x7e1028a0 ) 
   #define A2W_SMPS_CTLA0R_MASK                                  0x00ffffff
   #define A2W_SMPS_CTLA0R_WIDTH                                 24
   #define A2W_SMPS_CTLA0R_RESET                                 0000000000
#define A2W_SMPS_CTLA1R                                          HW_REGISTER_RW( 0x7e1028a4 ) 
   #define A2W_SMPS_CTLA1R_MASK                                  0x00ffffff
   #define A2W_SMPS_CTLA1R_WIDTH                                 24
   #define A2W_SMPS_CTLA1R_RESET                                 0000000000
#define A2W_SMPS_CTLA2R                                          HW_REGISTER_RW( 0x7e1028a8 ) 
   #define A2W_SMPS_CTLA2R_MASK                                  0x00ffffff
   #define A2W_SMPS_CTLA2R_WIDTH                                 24
   #define A2W_SMPS_CTLA2R_RESET                                 0000000000
#define A2W_SMPS_CTLB0R                                          HW_REGISTER_RW( 0x7e1028b0 ) 
   #define A2W_SMPS_CTLB0R_MASK                                  0x00ffffff
   #define A2W_SMPS_CTLB0R_WIDTH                                 24
   #define A2W_SMPS_CTLB0R_RESET                                 0000000000
#define A2W_SMPS_CTLB1R                                          HW_REGISTER_RW( 0x7e1028b4 ) 
   #define A2W_SMPS_CTLB1R_MASK                                  0x00ffffff
   #define A2W_SMPS_CTLB1R_WIDTH                                 24
   #define A2W_SMPS_CTLB1R_RESET                                 0000000000
#define A2W_SMPS_CTLB2R                                          HW_REGISTER_RW( 0x7e1028b8 ) 
   #define A2W_SMPS_CTLB2R_MASK                                  0x00ffffff
   #define A2W_SMPS_CTLB2R_WIDTH                                 24
   #define A2W_SMPS_CTLB2R_RESET                                 0000000000
#define A2W_SMPS_CTLC0R                                          HW_REGISTER_RW( 0x7e1028c0 ) 
   #define A2W_SMPS_CTLC0R_MASK                                  0x00ffffff
   #define A2W_SMPS_CTLC0R_WIDTH                                 24
   #define A2W_SMPS_CTLC0R_RESET                                 0000000000
#define A2W_SMPS_CTLC1R                                          HW_REGISTER_RW( 0x7e1028c4 ) 
   #define A2W_SMPS_CTLC1R_MASK                                  0x00ffffff
   #define A2W_SMPS_CTLC1R_WIDTH                                 24
   #define A2W_SMPS_CTLC1R_RESET                                 0000000000
#define A2W_SMPS_CTLC2R                                          HW_REGISTER_RW( 0x7e1028c8 ) 
   #define A2W_SMPS_CTLC2R_MASK                                  0x00ffffff
   #define A2W_SMPS_CTLC2R_WIDTH                                 24
   #define A2W_SMPS_CTLC2R_RESET                                 0000000000
#define A2W_SMPS_CTLC3R                                          HW_REGISTER_RW( 0x7e1028cc ) 
   #define A2W_SMPS_CTLC3R_MASK                                  0x00ffffff
   #define A2W_SMPS_CTLC3R_WIDTH                                 24
   #define A2W_SMPS_CTLC3R_RESET                                 0000000000
#define A2W_SMPS_LDO0R                                           HW_REGISTER_RW( 0x7e1028d0 ) 
   #define A2W_SMPS_LDO0R_MASK                                   0x00ffffff
   #define A2W_SMPS_LDO0R_WIDTH                                  24
   #define A2W_SMPS_LDO0R_RESET                                  0000000000
#define A2W_SMPS_LDO1R                                           HW_REGISTER_RW( 0x7e1028d4 ) 
   #define A2W_SMPS_LDO1R_MASK                                   0x00ffffff
   #define A2W_SMPS_LDO1R_WIDTH                                  24
   #define A2W_SMPS_LDO1R_RESET                                  0000000000
#define A2W_PLLA_CTRLR                                           HW_REGISTER_RW( 0x7e102900 ) 
   #define A2W_PLLA_CTRLR_MASK                                   0x000373ff
   #define A2W_PLLA_CTRLR_WIDTH                                  18
   #define A2W_PLLA_CTRLR_RESET                                  0000000000
#define A2W_PLLA_FRACR                                           HW_REGISTER_RW( 0x7e102a00 ) 
   #define A2W_PLLA_FRACR_MASK                                   0x000fffff
   #define A2W_PLLA_FRACR_WIDTH                                  20
   #define A2W_PLLA_FRACR_RESET                                  0000000000
#define A2W_PLLA_DSI0R                                           HW_REGISTER_RW( 0x7e102b00 ) 
   #define A2W_PLLA_DSI0R_MASK                                   0x000003ff
   #define A2W_PLLA_DSI0R_WIDTH                                  10
   #define A2W_PLLA_DSI0R_RESET                                  0000000000
#define A2W_PLLA_CORER                                           HW_REGISTER_RW( 0x7e102c00 ) 
   #define A2W_PLLA_CORER_MASK                                   0x000003ff
   #define A2W_PLLA_CORER_WIDTH                                  10
   #define A2W_PLLA_CORER_RESET                                  0000000000
#define A2W_PLLA_PERR                                            HW_REGISTER_RW( 0x7e102d00 ) 
   #define A2W_PLLA_PERR_MASK                                    0x000003ff
   #define A2W_PLLA_PERR_WIDTH                                   10
   #define A2W_PLLA_PERR_RESET                                   0000000000
#define A2W_PLLA_CCP2R                                           HW_REGISTER_RW( 0x7e102e00 ) 
   #define A2W_PLLA_CCP2R_MASK                                   0x000003ff
   #define A2W_PLLA_CCP2R_WIDTH                                  10
   #define A2W_PLLA_CCP2R_RESET                                  0000000000
#define A2W_PLLA_MULTI                                           HW_REGISTER_RW( 0x7e102f00 ) 
   #define A2W_PLLA_MULTI_MASK                                   0000000000
   #define A2W_PLLA_MULTI_WIDTH                                  0
   #define A2W_PLLA_MULTI_RESET                                  0000000000
#define A2W_PLLC_CTRLR                                           HW_REGISTER_RW( 0x7e102920 ) 
   #define A2W_PLLC_CTRLR_MASK                                   0x000373ff
   #define A2W_PLLC_CTRLR_WIDTH                                  18
   #define A2W_PLLC_CTRLR_RESET                                  0000000000
#define A2W_PLLC_FRACR                                           HW_REGISTER_RW( 0x7e102a20 ) 
   #define A2W_PLLC_FRACR_MASK                                   0x000fffff
   #define A2W_PLLC_FRACR_WIDTH                                  20
   #define A2W_PLLC_FRACR_RESET                                  0000000000
#define A2W_PLLC_CORE2R                                          HW_REGISTER_RW( 0x7e102b20 ) 
   #define A2W_PLLC_CORE2R_MASK                                  0x000003ff
   #define A2W_PLLC_CORE2R_WIDTH                                 10
   #define A2W_PLLC_CORE2R_RESET                                 0000000000
#define A2W_PLLC_CORE1R                                          HW_REGISTER_RW( 0x7e102c20 ) 
   #define A2W_PLLC_CORE1R_MASK                                  0x000003ff
   #define A2W_PLLC_CORE1R_WIDTH                                 10
   #define A2W_PLLC_CORE1R_RESET                                 0000000000
#define A2W_PLLC_PERR                                            HW_REGISTER_RW( 0x7e102d20 ) 
   #define A2W_PLLC_PERR_MASK                                    0x000003ff
   #define A2W_PLLC_PERR_WIDTH                                   10
   #define A2W_PLLC_PERR_RESET                                   0000000000
#define A2W_PLLC_CORE0R                                          HW_REGISTER_RW( 0x7e102e20 ) 
   #define A2W_PLLC_CORE0R_MASK                                  0x000003ff
   #define A2W_PLLC_CORE0R_WIDTH                                 10
   #define A2W_PLLC_CORE0R_RESET                                 0000000000
#define A2W_PLLC_MULTI                                           HW_REGISTER_RW( 0x7e102f20 ) 
   #define A2W_PLLC_MULTI_MASK                                   0000000000
   #define A2W_PLLC_MULTI_WIDTH                                  0
   #define A2W_PLLC_MULTI_RESET                                  0000000000
#define A2W_PLLD_CTRLR                                           HW_REGISTER_RW( 0x7e102940 ) 
   #define A2W_PLLD_CTRLR_MASK                                   0x000373ff
   #define A2W_PLLD_CTRLR_WIDTH                                  18
   #define A2W_PLLD_CTRLR_RESET                                  0000000000
#define A2W_PLLD_FRACR                                           HW_REGISTER_RW( 0x7e102a40 ) 
   #define A2W_PLLD_FRACR_MASK                                   0x000fffff
   #define A2W_PLLD_FRACR_WIDTH                                  20
   #define A2W_PLLD_FRACR_RESET                                  0000000000
#define A2W_PLLD_DSI0R                                           HW_REGISTER_RW( 0x7e102b40 ) 
   #define A2W_PLLD_DSI0R_MASK                                   0x000003ff
   #define A2W_PLLD_DSI0R_WIDTH                                  10
   #define A2W_PLLD_DSI0R_RESET                                  0000000000
#define A2W_PLLD_CORER                                           HW_REGISTER_RW( 0x7e102c40 ) 
   #define A2W_PLLD_CORER_MASK                                   0x000003ff
   #define A2W_PLLD_CORER_WIDTH                                  10
   #define A2W_PLLD_CORER_RESET                                  0000000000
#define A2W_PLLD_PERR                                            HW_REGISTER_RW( 0x7e102d40 ) 
   #define A2W_PLLD_PERR_MASK                                    0x000003ff
   #define A2W_PLLD_PERR_WIDTH                                   10
   #define A2W_PLLD_PERR_RESET                                   0000000000
#define A2W_PLLD_DSI1R                                           HW_REGISTER_RW( 0x7e102e40 ) 
   #define A2W_PLLD_DSI1R_MASK                                   0x000003ff
   #define A2W_PLLD_DSI1R_WIDTH                                  10
   #define A2W_PLLD_DSI1R_RESET                                  0000000000
#define A2W_PLLD_MULTI                                           HW_REGISTER_RW( 0x7e102f40 ) 
   #define A2W_PLLD_MULTI_MASK                                   0000000000
   #define A2W_PLLD_MULTI_WIDTH                                  0
   #define A2W_PLLD_MULTI_RESET                                  0000000000
#define A2W_PLLH_CTRLR                                           HW_REGISTER_RW( 0x7e102960 ) 
   #define A2W_PLLH_CTRLR_MASK                                   0x000370ff
   #define A2W_PLLH_CTRLR_WIDTH                                  18
   #define A2W_PLLH_CTRLR_RESET                                  0000000000
#define A2W_PLLH_FRACR                                           HW_REGISTER_RW( 0x7e102a60 ) 
   #define A2W_PLLH_FRACR_MASK                                   0x000fffff
   #define A2W_PLLH_FRACR_WIDTH                                  20
   #define A2W_PLLH_FRACR_RESET                                  0000000000
#define A2W_PLLH_AUXR                                            HW_REGISTER_RW( 0x7e102b60 ) 
   #define A2W_PLLH_AUXR_MASK                                    0x000003ff
   #define A2W_PLLH_AUXR_WIDTH                                   10
   #define A2W_PLLH_AUXR_RESET                                   0000000000
#define A2W_PLLH_RCALR                                           HW_REGISTER_RW( 0x7e102c60 ) 
   #define A2W_PLLH_RCALR_MASK                                   0x000003ff
   #define A2W_PLLH_RCALR_WIDTH                                  10
   #define A2W_PLLH_RCALR_RESET                                  0000000000
#define A2W_PLLH_PIXR                                            HW_REGISTER_RW( 0x7e102d60 ) 
   #define A2W_PLLH_PIXR_MASK                                    0x000003ff
   #define A2W_PLLH_PIXR_WIDTH                                   10
   #define A2W_PLLH_PIXR_RESET                                   0000000000
#define A2W_PLLH_STSR                                            HW_REGISTER_RW( 0x7e102e60 ) 
   #define A2W_PLLH_STSR_MASK                                    0xffffffff
   #define A2W_PLLH_STSR_WIDTH                                   32
   #define A2W_PLLH_STSR_RESET                                   0000000000
#define A2W_XOSC_CTRLR                                           HW_REGISTER_RW( 0x7e102990 ) 
   #define A2W_XOSC_CTRLR_MASK                                   0x0000037f
   #define A2W_XOSC_CTRLR_WIDTH                                  10
   #define A2W_XOSC_CTRLR_RESET                                  0000000000
#define A2W_PLLH_MULTI                                           HW_REGISTER_RW( 0x7e102f60 ) 
   #define A2W_PLLH_MULTI_MASK                                   0000000000
   #define A2W_PLLH_MULTI_WIDTH                                  0
   #define A2W_PLLH_MULTI_RESET                                  0000000000
