// This file was generated by the create_regs script
#define H264_BASE                                                0x7f000000
#define H264_APB_ID                                              0x68323634
#define H264_RC                                                  HW_REGISTER_RW( 0x7f000000 ) 
   #define H264_RC_MASK                                          0xffffffff
   #define H264_RC_WIDTH                                         32
