// This file was generated by the create_regs script
#define HDCP_BASE                                                0x7e809000
#define HDCP_APB_ID                                              0x48444350
#define HDCP_KEY_CTL                                             HW_REGISTER_RW( 0x7e809000 ) 
   #define HDCP_KEY_CTL_MASK                                     0x00000007
   #define HDCP_KEY_CTL_WIDTH                                    3
   #define HDCP_KEY_CTL_RESET                                    0000000000
      #define HDCP_KEY_CTL_START_BITS                            0:0
      #define HDCP_KEY_CTL_START_SET                             0x00000001
      #define HDCP_KEY_CTL_START_CLR                             0xfffffffe
      #define HDCP_KEY_CTL_START_MSB                             0
      #define HDCP_KEY_CTL_START_LSB                             0
      #define HDCP_KEY_CTL_START_RESET                           0x0
      #define HDCP_KEY_CTL_DONE_BITS                             1:1
      #define HDCP_KEY_CTL_DONE_SET                              0x00000002
      #define HDCP_KEY_CTL_DONE_CLR                              0xfffffffd
      #define HDCP_KEY_CTL_DONE_MSB                              1
      #define HDCP_KEY_CTL_DONE_LSB                              1
      #define HDCP_KEY_CTL_DONE_RESET                            0x0
      #define HDCP_KEY_CTL_DISHDCP_BITS                          2:2
      #define HDCP_KEY_CTL_DISHDCP_SET                           0x00000004
      #define HDCP_KEY_CTL_DISHDCP_CLR                           0xfffffffb
      #define HDCP_KEY_CTL_DISHDCP_MSB                           2
      #define HDCP_KEY_CTL_DISHDCP_LSB                           2
      #define HDCP_KEY_CTL_DISHDCP_RESET                         0x0
#define HDCP_KEY_ADR                                             HW_REGISTER_RW( 0x7e809004 ) 
   #define HDCP_KEY_ADR_MASK                                     0x000000ff
   #define HDCP_KEY_ADR_WIDTH                                    8
   #define HDCP_KEY_ADR_RESET                                    0000000000
#define HDCP_KEY_KY0                                             HW_REGISTER_RW( 0x7e809008 ) 
   #define HDCP_KEY_KY0_MASK                                     0xffffffff
   #define HDCP_KEY_KY0_WIDTH                                    32
   #define HDCP_KEY_KY0_RESET                                    0000000000
#define HDCP_KEY_KY1                                             HW_REGISTER_RW( 0x7e80900c ) 
   #define HDCP_KEY_KY1_MASK                                     0x00ffffff
   #define HDCP_KEY_KY1_WIDTH                                    24
   #define HDCP_KEY_KY1_RESET                                    0000000000
