// This file was generated by the create_regs script
#define I2C1_BASE                                                0x7e804000
#define I2C1_C                                                   HW_REGISTER_RW( 0x7e804000 ) 
   #define I2C1_C_MASK                                           0x00008701
   #define I2C1_C_WIDTH                                          16
   #define I2C1_C_RESET                                          0000000000
#define I2C1_S                                                   HW_REGISTER_RW( 0x7e804004 ) 
   #define I2C1_S_MASK                                           0xffffffff
   #define I2C1_S_WIDTH                                          32
   #define I2C1_S_RESET                                          0x00000050
#define I2C1_DLEN                                                HW_REGISTER_RW( 0x7e804008 ) 
   #define I2C1_DLEN_MASK                                        0x0000ffff
   #define I2C1_DLEN_WIDTH                                       16
   #define I2C1_DLEN_RESET                                       0000000000
#define I2C1_A                                                   HW_REGISTER_RW( 0x7e80400c ) 
   #define I2C1_A_MASK                                           0x0000007f
   #define I2C1_A_WIDTH                                          7
   #define I2C1_A_RESET                                          0000000000
#define I2C1_FIFO                                                HW_REGISTER_RW( 0x7e804010 ) 
   #define I2C1_FIFO_MASK                                        0x000000ff
   #define I2C1_FIFO_WIDTH                                       8
   #define I2C1_FIFO_RESET                                       0000000000
#define I2C1_DIV                                                 HW_REGISTER_RW( 0x7e804014 ) 
   #define I2C1_DIV_MASK                                         0x0000ffff
   #define I2C1_DIV_WIDTH                                        16
   #define I2C1_DIV_RESET                                        0x000005dc
#define I2C1_DEL                                                 HW_REGISTER_RW( 0x7e804018 ) 
   #define I2C1_DEL_MASK                                         0xffffffff
   #define I2C1_DEL_WIDTH                                        32
   #define I2C1_DEL_RESET                                        0x00300030
#define I2C1_CLKT                                                HW_REGISTER_RW( 0x7e80401c ) 
   #define I2C1_CLKT_MASK                                        0x0000ffff
   #define I2C1_CLKT_WIDTH                                       16
   #define I2C1_CLKT_RESET                                       0x00000040
