// This file was generated by the create_regs script
#define I2C2_BASE                                                0x7e805000
#define I2C2_C                                                   HW_REGISTER_RW( 0x7e805000 ) 
   #define I2C2_C_MASK                                           0x00008701
   #define I2C2_C_WIDTH                                          16
   #define I2C2_C_RESET                                          0000000000
#define I2C2_S                                                   HW_REGISTER_RW( 0x7e805004 ) 
   #define I2C2_S_MASK                                           0xffffffff
   #define I2C2_S_WIDTH                                          32
   #define I2C2_S_RESET                                          0x00000050
#define I2C2_DLEN                                                HW_REGISTER_RW( 0x7e805008 ) 
   #define I2C2_DLEN_MASK                                        0x0000ffff
   #define I2C2_DLEN_WIDTH                                       16
   #define I2C2_DLEN_RESET                                       0000000000
#define I2C2_A                                                   HW_REGISTER_RW( 0x7e80500c ) 
   #define I2C2_A_MASK                                           0x0000007f
   #define I2C2_A_WIDTH                                          7
   #define I2C2_A_RESET                                          0000000000
#define I2C2_FIFO                                                HW_REGISTER_RW( 0x7e805010 ) 
   #define I2C2_FIFO_MASK                                        0x000000ff
   #define I2C2_FIFO_WIDTH                                       8
   #define I2C2_FIFO_RESET                                       0000000000
#define I2C2_DIV                                                 HW_REGISTER_RW( 0x7e805014 ) 
   #define I2C2_DIV_MASK                                         0x0000ffff
   #define I2C2_DIV_WIDTH                                        16
   #define I2C2_DIV_RESET                                        0x000005dc
#define I2C2_DEL                                                 HW_REGISTER_RW( 0x7e805018 ) 
   #define I2C2_DEL_MASK                                         0xffffffff
   #define I2C2_DEL_WIDTH                                        32
   #define I2C2_DEL_RESET                                        0x00300030
#define I2C2_CLKT                                                HW_REGISTER_RW( 0x7e80501c ) 
   #define I2C2_CLKT_MASK                                        0x0000ffff
   #define I2C2_CLKT_WIDTH                                       16
   #define I2C2_CLKT_RESET                                       0x00000040
