// This file was generated by the create_regs script
#define NU_BASE                                                  0x7e008000
#define NU_HOSTIO_OF                                             HW_REGISTER_RW( 0x7e008000 ) 
   #define NU_HOSTIO_OF_MASK                                     0xffffffff
   #define NU_HOSTIO_OF_WIDTH                                    32
   #define NU_HOSTIO_OF_RESET                                    0000000000
