// This file was generated by the create_regs script
#define OTP_BASE                                                 0x7e20f000
#define OTP_APB_ID                                               0x206f7470
#define OTP_BOOTMODE_REG                                         HW_REGISTER_RW( 0x7e20f000 ) 
   #define OTP_BOOTMODE_REG_MASK                                 0xffffffff
   #define OTP_BOOTMODE_REG_WIDTH                                32
#define OTP_CONFIG_REG                                           HW_REGISTER_RW( 0x7e20f004 ) 
   #define OTP_CONFIG_REG_MASK                                   0x00000007
   #define OTP_CONFIG_REG_WIDTH                                  3
#define OTP_CTRL_LO_REG                                          HW_REGISTER_RW( 0x7e20f008 ) 
   #define OTP_CTRL_LO_REG_MASK                                  0xffffffff
   #define OTP_CTRL_LO_REG_WIDTH                                 32
#define OTP_CTRL_HI_REG                                          HW_REGISTER_RW( 0x7e20f00c ) 
   #define OTP_CTRL_HI_REG_MASK                                  0x0000ffff
   #define OTP_CTRL_HI_REG_WIDTH                                 16
#define OTP_STATUS_REG                                           HW_REGISTER_RO( 0x7e20f010 ) 
   #define OTP_STATUS_REG_MASK                                   0xffffffff
   #define OTP_STATUS_REG_WIDTH                                  32
#define OTP_BITSEL_REG                                           HW_REGISTER_RW( 0x7e20f014 ) 
   #define OTP_BITSEL_REG_MASK                                   0x0000001f
   #define OTP_BITSEL_REG_WIDTH                                  5
#define OTP_DATA_REG                                             HW_REGISTER_RW( 0x7e20f018 ) 
   #define OTP_DATA_REG_MASK                                     0x0000001f
   #define OTP_DATA_REG_WIDTH                                    5
#define OTP_ADDR_REG                                             HW_REGISTER_RW( 0x7e20f01c ) 
   #define OTP_ADDR_REG_MASK                                     0x0000001f
   #define OTP_ADDR_REG_WIDTH                                    5
#define OTP_WRITE_DATA_READ_REG                                  HW_REGISTER_RW( 0x7e20f020 ) 
   #define OTP_WRITE_DATA_READ_REG_MASK                          0xffffffff
   #define OTP_WRITE_DATA_READ_REG_WIDTH                         32
#define OTP_INIT_STATUS_REG                                      HW_REGISTER_RW( 0x7e20f024 ) 
   #define OTP_INIT_STATUS_REG_MASK                              0xffffffff
   #define OTP_INIT_STATUS_REG_WIDTH                             32
