// This file was generated by the create_regs script
#define PIXELVALVE2_BASE                                         0x7e807000
#define PIXELVALVE2_APB_ID                                       0x70697876
#define PIXELVALVE2_C                                            HW_REGISTER_RW( 0x7e807000 ) 
   #define PIXELVALVE2_C_MASK                                    0x00ffffff
   #define PIXELVALVE2_C_WIDTH                                   24
#define PIXELVALVE2_VC                                           HW_REGISTER_RW( 0x7e807004 ) 
   #define PIXELVALVE2_VC_MASK                                   0x007fffff
   #define PIXELVALVE2_VC_WIDTH                                  23
#define PIXELVALVE2_VSYNCD_EVEN                                  HW_REGISTER_RW( 0x7e807008 ) 
   #define PIXELVALVE2_VSYNCD_EVEN_MASK                          0x0001ffff
   #define PIXELVALVE2_VSYNCD_EVEN_WIDTH                         17
#define PIXELVALVE2_HORZA                                        HW_REGISTER_RW( 0x7e80700c ) 
   #define PIXELVALVE2_HORZA_MASK                                0xffffffff
   #define PIXELVALVE2_HORZA_WIDTH                               32
#define PIXELVALVE2_HORZB                                        HW_REGISTER_RW( 0x7e807010 ) 
   #define PIXELVALVE2_HORZB_MASK                                0xffffffff
   #define PIXELVALVE2_HORZB_WIDTH                               32
#define PIXELVALVE2_VERTA                                        HW_REGISTER_RW( 0x7e807014 ) 
   #define PIXELVALVE2_VERTA_MASK                                0xffffffff
   #define PIXELVALVE2_VERTA_WIDTH                               32
#define PIXELVALVE2_VERTB                                        HW_REGISTER_RW( 0x7e807018 ) 
   #define PIXELVALVE2_VERTB_MASK                                0xffffffff
   #define PIXELVALVE2_VERTB_WIDTH                               32
#define PIXELVALVE2_VERTA_EVEN                                   HW_REGISTER_RW( 0x7e80701c ) 
   #define PIXELVALVE2_VERTA_EVEN_MASK                           0xffffffff
   #define PIXELVALVE2_VERTA_EVEN_WIDTH                          32
#define PIXELVALVE2_VERTB_EVEN                                   HW_REGISTER_RW( 0x7e807020 ) 
   #define PIXELVALVE2_VERTB_EVEN_MASK                           0xffffffff
   #define PIXELVALVE2_VERTB_EVEN_WIDTH                          32
#define PIXELVALVE2_INTEN                                        HW_REGISTER_RW( 0x7e807024 ) 
   #define PIXELVALVE2_INTEN_MASK                                0x000003ff
   #define PIXELVALVE2_INTEN_WIDTH                               10
#define PIXELVALVE2_INTSTAT                                      HW_REGISTER_RW( 0x7e807028 ) 
   #define PIXELVALVE2_INTSTAT_MASK                              0x000003ff
   #define PIXELVALVE2_INTSTAT_WIDTH                             10
#define PIXELVALVE2_STAT                                         HW_REGISTER_RW( 0x7e80702c ) 
   #define PIXELVALVE2_STAT_MASK                                 0x000003ff
   #define PIXELVALVE2_STAT_WIDTH                                10
#define PIXELVALVE2_DSI_HACT_ACT                                 HW_REGISTER_RW( 0x7e807030 ) 
   #define PIXELVALVE2_DSI_HACT_ACT_MASK                         0x0000ffff
   #define PIXELVALVE2_DSI_HACT_ACT_WIDTH                        16
