// This file was generated by the create_regs script
#define PIXELVALVE0_BASE                                         0x7e206000
#define PIXELVALVE0_APB_ID                                       0x70697876
#define PIXELVALVE0_C                                            HW_REGISTER_RW( 0x7e206000 ) 
   #define PIXELVALVE0_C_MASK                                    0x00ffffff
   #define PIXELVALVE0_C_WIDTH                                   24
#define PIXELVALVE0_VC                                           HW_REGISTER_RW( 0x7e206004 ) 
   #define PIXELVALVE0_VC_MASK                                   0x007fffff
   #define PIXELVALVE0_VC_WIDTH                                  23
#define PIXELVALVE0_VSYNCD_EVEN                                  HW_REGISTER_RW( 0x7e206008 ) 
   #define PIXELVALVE0_VSYNCD_EVEN_MASK                          0x0001ffff
   #define PIXELVALVE0_VSYNCD_EVEN_WIDTH                         17
#define PIXELVALVE0_HORZA                                        HW_REGISTER_RW( 0x7e20600c ) 
   #define PIXELVALVE0_HORZA_MASK                                0xffffffff
   #define PIXELVALVE0_HORZA_WIDTH                               32
#define PIXELVALVE0_HORZB                                        HW_REGISTER_RW( 0x7e206010 ) 
   #define PIXELVALVE0_HORZB_MASK                                0xffffffff
   #define PIXELVALVE0_HORZB_WIDTH                               32
#define PIXELVALVE0_VERTA                                        HW_REGISTER_RW( 0x7e206014 ) 
   #define PIXELVALVE0_VERTA_MASK                                0xffffffff
   #define PIXELVALVE0_VERTA_WIDTH                               32
#define PIXELVALVE0_VERTB                                        HW_REGISTER_RW( 0x7e206018 ) 
   #define PIXELVALVE0_VERTB_MASK                                0xffffffff
   #define PIXELVALVE0_VERTB_WIDTH                               32
#define PIXELVALVE0_VERTA_EVEN                                   HW_REGISTER_RW( 0x7e20601c ) 
   #define PIXELVALVE0_VERTA_EVEN_MASK                           0xffffffff
   #define PIXELVALVE0_VERTA_EVEN_WIDTH                          32
#define PIXELVALVE0_VERTB_EVEN                                   HW_REGISTER_RW( 0x7e206020 ) 
   #define PIXELVALVE0_VERTB_EVEN_MASK                           0xffffffff
   #define PIXELVALVE0_VERTB_EVEN_WIDTH                          32
#define PIXELVALVE0_INTEN                                        HW_REGISTER_RW( 0x7e206024 ) 
   #define PIXELVALVE0_INTEN_MASK                                0x000003ff
   #define PIXELVALVE0_INTEN_WIDTH                               10
#define PIXELVALVE0_INTSTAT                                      HW_REGISTER_RW( 0x7e206028 ) 
   #define PIXELVALVE0_INTSTAT_MASK                              0x000003ff
   #define PIXELVALVE0_INTSTAT_WIDTH                             10
#define PIXELVALVE0_STAT                                         HW_REGISTER_RW( 0x7e20602c ) 
   #define PIXELVALVE0_STAT_MASK                                 0x000003ff
   #define PIXELVALVE0_STAT_WIDTH                                10
#define PIXELVALVE0_DSI_HACT_ACT                                 HW_REGISTER_RW( 0x7e206030 ) 
   #define PIXELVALVE0_DSI_HACT_ACT_MASK                         0x0000ffff
   #define PIXELVALVE0_DSI_HACT_ACT_WIDTH                        16
