// This file was generated by the create_regs script
#define TE_BASE                                                  0x7e20e000
#define TE_APB_ID                                                0x00746563
#define TE_0C                                                    HW_REGISTER_RW( 0x7e20e000 ) 
   #define TE_0C_MASK                                            0xffffffff
   #define TE_0C_WIDTH                                           32
#define TE_0VSWIDTH                                              HW_REGISTER_RW( 0x7e20e004 ) 
   #define TE_0VSWIDTH_MASK                                      0xffffffff
   #define TE_0VSWIDTH_WIDTH                                     32
#define TE_1C                                                    HW_REGISTER_RW( 0x7e20e008 ) 
   #define TE_1C_MASK                                            0xffffffff
   #define TE_1C_WIDTH                                           32
#define TE_1VSWIDTH                                              HW_REGISTER_RW( 0x7e20e00c ) 
   #define TE_1VSWIDTH_MASK                                      0xffffffff
   #define TE_1VSWIDTH_WIDTH                                     32
#define TE_2C                                                    HW_REGISTER_RW( 0x7e20e010 ) 
   #define TE_2C_MASK                                            0xffffffff
   #define TE_2C_WIDTH                                           32
#define TE_2VSWIDTH                                              HW_REGISTER_RW( 0x7e20e014 ) 
   #define TE_2VSWIDTH_MASK                                      0xffffffff
   #define TE_2VSWIDTH_WIDTH                                     32
